Repository javaistic/javaistic, pull requests merged in 2025-08, with the labels that each got.

#736 Add particle effect and animations to homepage
  bun.lock
  package.json
  src/app/(site)/page.tsx
  src/components/Particles.tsx
Labels: 🔥 enhancement, GSSoC, GSSoC'25, level2

#737 Add Prettier for code formatting and improve Java documentation
  .prettierrc
  bun.lock
  content/docs/arrays.mdx
  content/docs/basic-input-output.mdx
  content/docs/break-statement.mdx
  content/docs/class-objects.mdx
  content/docs/comments.mdx
  content/docs/constructors.mdx
  content/docs/continue-statement.mdx
  content/docs/enhanced-for-loop.mdx
  content/docs/expressions-statements-blocks.mdx
  content/docs/final-keyword.mdx
  content/docs/for-loop.mdx
  content/docs/hello-world.mdx
  content/docs/if-else-statement.mdx
  content/docs/index.mdx
  content/docs/installation.mdx
  content/docs/introduction.mdx
  content/docs/jvm-jre-jdk.mdx
  content/docs/method-overloading.mdx
  content/docs/methods.mdx
  content/docs/multidimensional-arrays.mdx
  content/docs/operators.mdx
  content/docs/static-keyword.mdx
  content/docs/switch-statement.mdx
  content/docs/this-keyword.mdx
  content/docs/variables-and-literals.mdx
  content/docs/variables-primitive-data-types.mdx
  content/docs/while-and-do-while-loop.mdx
  content/programs/add-two-integers.mdx
  content/programs/calculate-compound-interest.mdx
  content/programs/calculate-power-of-a-number.mdx
  content/programs/calculate-simple-interest.mdx
  content/programs/check-even-or-odd.mdx
  content/programs/factorial-in-java.mdx
  content/programs/find-quotient-and-reminder.mdx
  content/programs/index.mdx
  content/programs/java-program-to-add-two-binary-numbers.mdx
  content/programs/java-program-to-add-two-complex-numbers.mdx
  content/programs/java-program-to-check-Leap-year.mdx
  content/programs/java-program-to-check-divisbility.mdx
  content/programs/java-program-to-find-nth-fibonacci-number.mdx
  content/programs/multiply-two-numbers.mdx
  content/programs/print-an-integer.mdx
  package.json
  src/app/(site)/page.tsx
  src/app/docs/layout.tsx
  src/components/Particles.tsx
  src/components/footer.tsx
  src/components/icons.tsx
  src/components/ui/button.tsx
Labels: 📖 docs, 🔥 enhancement, dependencies

#740 Implement advanced search API and custom search dialog
  src/app/api/search/route.ts
  src/app/global.css
  src/app/layout.tsx
  src/app/static.json/route.ts
  src/components/search.tsx
Labels: 🔥 enhancement

#742 Enhance metadata generation with Open Graph and Twitter card support
  public/og.png
  src/app/docs/[[...slug]]/page.tsx
  src/app/layout.tsx
  src/app/programs/[[...slug]]/page.tsx
Labels: 🔥 enhancement, seo

#743 Add Java program to check whether an input character is a vowel or consonant
  content/programs/java-program-to-check-whether-input-character-is-vowel-or-consonant.mdx
  content/programs/meta.json
Labels: 📖 docs, programs, GSSoC, GSSoC'25, level2

#747 Add Privacy Policy and Terms of Service Page
  src/app/(site)/layout.tsx
  src/app/(site)/legal/privacy/page.tsx
  src/app/(site)/legal/terms/page.tsx
  src/components/footer.tsx
Labels: 🔥 enhancement, GSSoC, GSSoC'25, level2

#748 Add Java IDE to website
  bun.lock
  package.json
  src/app/api/playground/route.ts
  src/app/layout.config.tsx
  src/app/playground/layout.tsx
  src/app/playground/page.tsx
  src/components/footer.tsx
  tsconfig.json
Labels: 🔥 enhancement, GSSoC, GSSoC'25, level3
