Repository javaistic/javaistic, pull requests merged in 2025-07, with the labels that each got.

#720 Add comprehensive Java tutorials and improve documentation structure
  content/docs/arrays.mdx
  content/docs/basic-input-output.mdx
  content/docs/break-statement.mdx
  content/docs/class-objects.mdx
  content/docs/comments.mdx
  content/docs/constructors.mdx
  content/docs/continue-statement.mdx
  content/docs/enhanced-for-loop.mdx
  content/docs/expressions-statements-blocks.mdx
  content/docs/final-keyword.mdx
  content/docs/for-loop.mdx
  content/docs/hello-world.mdx
  content/docs/if-else-statement.mdx
  content/docs/index.mdx
  content/docs/installation.mdx
  content/docs/introduction.mdx
  content/docs/jvm-jre-jdk.mdx
  content/docs/meta.json
  content/docs/method-overloading.mdx
  content/docs/methods.mdx
  content/docs/multidimensional-arrays.mdx
  content/docs/operators.mdx
  content/docs/static-keyword.mdx
  content/docs/switch-statement.mdx
  content/docs/test.mdx
  content/docs/this-keyword.mdx
  content/docs/variables-and-literals.mdx
  content/docs/variables-primitive-data-types.mdx
  content/docs/while-and-do-while-loop.mdx
  public/img/docs/jvm-jre-jdk/1.svg
  public/img/docs/jvm-jre-jdk/2.svg
  public/img/docs/jvm-jre-jdk/3.svg
  public/img/docs/jvm-jre-jdk/4.svg
  public/img/docs/switch-case-flowchart.svg
  public/img/docs/working-of-for-loop.svg
  public/img/docs/wroking-of-if-else-statement.svg
  public/img/docs/wroking-of-java-if-statement.svg
  src/app/docs/layout.tsx
  src/mdx-components.tsx
Labels: 📖 docs, 🔥 enhancement

#726 Add dual licensing structure with separate license files
  LICENSE-AGPL.md
  LICENSE-CC.md
  LICENSE.md
Labels: 🔥 enhancement

#728 Enhance layout, branding and add social icons components
  src/app/(site)/layout.tsx
  src/app/(site)/page.tsx
  src/app/layout.config.tsx
  src/app/layout.tsx
  src/components/footer.tsx
  src/components/icons.tsx
  src/components/logo.tsx
Labels: 📖 docs, 🔥 enhancement, seo

#733 Add GSSoC 25 Contribution Rules
  CONTRIBUTION_RULES_GSSOC25.md
Labels: GSSoC, GSSoC'25

#732 Add Hover Lift & Transition Styling to Cards Under “Why learn Java with Javaistic?”
  src/app/(site)/page.tsx
Labels: GSSoC, GSSoC'25, level1

#735 Implement sitemap and robots.txt generation functionality
  public/robots.txt
  public/sitemap.xml
  public/urllist.txt
  src/app/robots.ts
  src/app/sitemap.ts
  src/lib/metadata.ts
Labels: 🔥 enhancement, seo
